version: '3'

x-base: &base
    env_file:
        - .env

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  django_app:
    build:
      context: django_app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"

  celery:
    build: ./django_app
    command: celery worker --app=core --loglevel=info
    volumes:
      - ./django_app:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
#    depends_on:
#      - web
#      - redis

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"