# Generated by Django 4.2.4 on 2023-08-22 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('code_monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkreport',
            name='script_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_report', to='code_monitoring.scriptcheck'),
        ),
    ]
