# Generated by Django 4.2.4 on 2023-08-21 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkreport',
            name='checking_script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checking_scripts', to='code_monitoring.scriptcheck'),
        ),
    ]
