# Generated by Django 4.2.4 on 2023-08-22 15:29

import code_monitoring.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_monitoring', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='file_path',
            field=models.FileField(upload_to=code_monitoring.models.generate_random_folder, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])], verbose_name='file_path'),
        ),
    ]
